# /.github/dependabot.yaml
# Configures GitHub's Dependabot.

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    # group all non-major dev dep updates together into a single PR
    groups:
      development-dependencies:
        dependency-type: development
        update-types: [minor, patch]
    # production dependencies and major updates to dev deps get their own PRs
