# /.github/dependabot.yaml
# Configures GitHub's Dependabot.

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    # group all updates together into a single PR (group name is "all")
    groups:
      all:
        patterns:
          - "*"
