nameexpress-rate-limit/.github/ISSUE_TEMPLATE/bug_report.yml: Report a bug
description: ———
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        # Thanks for reporting this bug!

        Help us replicate and find a fix for the issue by filling in this form.
  - type: textarea
    attributes:
      label: Description
      description: |
        Describe the issue and how to replicate it. If possible, please include
        a minimal example to reproduce the issue.
    validations:
      required: true
  - type: input
    attributes:
      label: Library version
      description: |
        Can be found the `express-rate-limit` field in the `dependencies` map of
        `package.json`
    validations:
      required: true
  - type: input
    attributes:
      label: Node version
      description: Output of the `node --version` command
    validations:
      required: true
  - type: input
    attributes:
      label: Typescript version (if you are using it)
      description: |
        Can be found the `typescript` field in the
        `dependencies`/`devDependencies` map of `package.json`
  - type: dropdown
    attributes:
      label: Module system
      description: |
        If you have `type: module` in your `package.json` file, then you are
        using ESM, else you are using CommonJS.
      options:
        - ESM
        - CommonJS
    validations:
      required: true
